{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uptick",
    "module": "uptick-android",
    "version": "2025.10.6+1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "uptick-android-2025.10.6+1.aar",
          "url": "uptick-android-2025.10.6+1.aar",
          "size": 310966,
          "sha512": "847216d81fffd1fa58d671453335577b03343bb0f0605b047ce64b2503d797a40724139d414057c95f7865c10d521cba0f6668cc0edaf60d7a0fc1ffc255ad37",
          "sha256": "58f05f91683b8e68fffce75fc8203e15997316d63ccb0594c0375663bed3f171",
          "sha1": "d3f22ff3c63e1a92588503c0d1ec7334bf84d15b",
          "md5": "13a2b2b9cea217495435f2ed2d77b20c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.2"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "uptick-android-2025.10.6+1.aar",
          "url": "uptick-android-2025.10.6+1.aar",
          "size": 310966,
          "sha512": "847216d81fffd1fa58d671453335577b03343bb0f0605b047ce64b2503d797a40724139d414057c95f7865c10d521cba0f6668cc0edaf60d7a0fc1ffc255ad37",
          "sha256": "58f05f91683b8e68fffce75fc8203e15997316d63ccb0594c0375663bed3f171",
          "sha1": "d3f22ff3c63e1a92588503c0d1ec7334bf84d15b",
          "md5": "13a2b2b9cea217495435f2ed2d77b20c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "uptick-android-2025.10.6+1-sources.jar",
          "url": "uptick-android-2025.10.6+1-sources.jar",
          "size": 110401,
          "sha512": "9e41b61e68111e2fc73a4ff50a28b0e9b20fb176b3fc31acb1286a3536c72ff8420041897908e595d99b695b79cfe89c0fb3d04f8111e8bc954a501dd71ff95b",
          "sha256": "79e317433d61ea95d8f9830a0fe99d4c16fc88288ed2024f4619088853d6362f",
          "sha1": "f4148312983efcdc1371f5de2df52fcb0ad6a114",
          "md5": "8ced63ef5ecbc948d42b0d9ed2597fa7"
        }
      ]
    }
  ]
}
