{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uptick",
    "module": "uptick-android",
    "version": "2025.10.7+1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "uptick-android-2025.10.7+1.aar",
          "url": "uptick-android-2025.10.7+1.aar",
          "size": 311516,
          "sha512": "0a16eb50b0a83678fbed1d37600a291d858579bd4bf424279117313112e8883c6e0113b0601a773c9eab101a65cce1f9481319962c9fc63788133c6ef1d2faa8",
          "sha256": "d17f3b3d1e69f9a327f63433246773a4417c99c390dd74753325464ad178c32a",
          "sha1": "0a3d645e0a8978a58e4fb92c0f2f5838ea3bb4b0",
          "md5": "13c3f6855755b3a3811081bea93504ea"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.2"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "uptick-android-2025.10.7+1.aar",
          "url": "uptick-android-2025.10.7+1.aar",
          "size": 311516,
          "sha512": "0a16eb50b0a83678fbed1d37600a291d858579bd4bf424279117313112e8883c6e0113b0601a773c9eab101a65cce1f9481319962c9fc63788133c6ef1d2faa8",
          "sha256": "d17f3b3d1e69f9a327f63433246773a4417c99c390dd74753325464ad178c32a",
          "sha1": "0a3d645e0a8978a58e4fb92c0f2f5838ea3bb4b0",
          "md5": "13c3f6855755b3a3811081bea93504ea"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "uptick-android-2025.10.7+1-sources.jar",
          "url": "uptick-android-2025.10.7+1-sources.jar",
          "size": 111417,
          "sha512": "aa750ac13fc616a416c668c3a7f1117ea14d0fb83366e27f52eafad47b2895fb0e15181f6c9d52a68c468440c24c4f04c31efc77dad62069b937a887e2b02033",
          "sha256": "63cb427a293401b37d6c6f284c51635ffebbbc95b032541952b68b220bebeb10",
          "sha1": "49ee9d8caf9b217706e08e837f21dceca3549f67",
          "md5": "0b9c70e46205dc525879052cc98dbe3a"
        }
      ]
    }
  ]
}
