{
  "formatVersion": "1.1",
  "component": {
    "group": "com.uptick",
    "module": "uptick-android",
    "version": "2025.10.6+2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "uptick-android-2025.10.6+2.aar",
          "url": "uptick-android-2025.10.6+2.aar",
          "size": 311510,
          "sha512": "29b5a1e83cce343c2d72c8715288245659018a8dfa7e14b8c4cf487d25d6c51003a6ada2ebe1b62ce60a1fc362c66d226f0234c29eacc9f618bbb91ae18dbb66",
          "sha256": "0d29464e735c12d0cfdc34399ff7e4fd0b57490b408aedeb956c3a2f88a25f1a",
          "sha1": "99c67383313ff398cb3c1e67325eac6d3ea16cdf",
          "md5": "cc314027db43fdc7f3f01285b019fb0f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.0.0-alpha.2"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "uptick-android-2025.10.6+2.aar",
          "url": "uptick-android-2025.10.6+2.aar",
          "size": 311510,
          "sha512": "29b5a1e83cce343c2d72c8715288245659018a8dfa7e14b8c4cf487d25d6c51003a6ada2ebe1b62ce60a1fc362c66d226f0234c29eacc9f618bbb91ae18dbb66",
          "sha256": "0d29464e735c12d0cfdc34399ff7e4fd0b57490b408aedeb956c3a2f88a25f1a",
          "sha1": "99c67383313ff398cb3c1e67325eac6d3ea16cdf",
          "md5": "cc314027db43fdc7f3f01285b019fb0f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "uptick-android-2025.10.6+2-sources.jar",
          "url": "uptick-android-2025.10.6+2-sources.jar",
          "size": 111417,
          "sha512": "aa750ac13fc616a416c668c3a7f1117ea14d0fb83366e27f52eafad47b2895fb0e15181f6c9d52a68c468440c24c4f04c31efc77dad62069b937a887e2b02033",
          "sha256": "63cb427a293401b37d6c6f284c51635ffebbbc95b032541952b68b220bebeb10",
          "sha1": "49ee9d8caf9b217706e08e837f21dceca3549f67",
          "md5": "0b9c70e46205dc525879052cc98dbe3a"
        }
      ]
    }
  ]
}
